### ISSUE TITLE
Separate ASAY and MSAY

### ISSUE THREAD

**Issue by Pdactyl** [HeavensGate/Eternal#103]
Do it, mister Woothie!

**Comment by Davnik** [comment]
Admins should see Asay and Msay. Mods should see Msay. Neither should see IC in OOC.

**Comment by Jacquar** [comment]
Ensure all custom roles see both unless otherwise stated. Sardi as headmod should see both.

**Comment by Davnik** [comment]
I imagine all custom roles will be given +ADMIN.

**Comment by Davnik** [comment]
Note on this issue. It's not actually an issue, and belongs in a much broader net.

ASAY is handled by +ADMIN, which is given to admins and mods.
MSAY is presumably handled by +MOD, which is given to admins and mods.

We will eventually need a list of what every permission gives access to, so that we can better tailor who has access to what with which permission flags.
