### ISSUE TITLE
Chromatics - Yes and Space Asshole (Lobby Musics)

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#232]
https://www.youtube.com/watch?v=ZKjtqJ-VO38
I'm approving this song for lobby music. The start and end are conveniently quiet, if we want to shrink it to a little under 180 seconds, though at one point we discussed a 5-minute lobby.

**Comment by Davnik** [comment]
Dropbox link, .mp3, might need to convert to .ogg

https://www.dropbox.com/s/5rp6ja65axo4pgv/CHROMATICS%20_YES_%20%28Love%20Theme%20From%20Lost%20River%29.mp3?dl=0

**Comment by Puckaboo2** [comment]
https://www.youtube.com/watch?v=IcUBI-YVRY8 Speeees asshoooooole.

**Comment by Jacquar** [comment]
Yes to Yes, no to Space Asshole. It's a funny song but inappropriate for HG on several levels, plus it's as bad as Space Oddity in terms of being overused in SS13 on certain servers. Players cringe at some of these songs because they're so repetitive. 

I prefer minimal vocals or none at all on our lobby music. Industrial or retro-cyberpunky stuff as a general theme, with hints of classic noir.

**Comment by Finriv** [comment]
It's still in the code anyway, like. The file is still there. It's just out of rotation.
