### ISSUE TITLE
Ghetto surgery tajaran claws

### ISSUE THREAD

**Issue by woothie** [HeavensGate/Eternal#36]
Be able to use tajaran claws for 25-50% chance as scalpel? We'd have to be careful, or people couldn't make normal attacks on downed foes with standard empty hands. Maybe only on help intent with a patient on a table (only surgery? that's not ghetto. increase % if surgery table?). Discuss.

**Comment by Davnik** [comment]
"patient on a table" referred to any table, and surgery tables... should probably increase all ghetto rolls anyway by a figure like 20%, since you can be more careful and directly monitor results/circumstances. Whether we choose to give a bonus for operating tables or a penalty for any other surfaces is kind of, like, our opinion, man.

**Comment by Davnik** [comment]
Discussion results: feline claws do more of a tearing than a slashing; they are somewhat blunt. We are in solid agreement (dav, static, mew, shingles) to remove this issue, and furthermore agree Tajaran claws should only Slash, not Edge.

**Comment by Davnik** [comment]
If we do implement this at some point in the future, mandatory 90-100% infection chance.
