### ISSUE TITLE
Hunt for typos and dumb descriptions for items

### ISSUE THREAD

**Issue by woothie** [HeavensGate/Eternal#52]
This is a big task, and anything found is to be reported to our loreteam. If you see any dumb descriptions (such as the blob) or typos while playing, please send in an ahelp, a PM on skype to anyone in core, or tell genchat.

**Comment by Jacquar** [comment]
Additionally/parallel to this, I will be manually trawling *the entire game* if I can find an easier means of doing so. At the moment, localhosting a server and using view-variables to filter only items that exist within the map is one option.

Doing it through dreammaker is a pain due to the network of rightclicks and the lack of a var search field compared to the ingame VV.

Any ideas on how I can make this job as painless as possible?

**Comment by woothie** [comment]
Get Notepad++ and search for the description value ( description=" I think
) in files. Ctrl-F -> Find in files.
I'll check an item in the code and find a specific phrase for you.

**Comment by Jacquar** [comment]
Notepad++ can open the files comfortably? Perfect. Thankye.

**Comment by Davnik** [comment]
I'd like to reference #90 here: Jakk's hunt for descriptions.

**Comment by Davnik** [comment]
This is part of a larger whole in 226.
